/*
 * Qase.io API
 *
 * You can use our API to access Qase.io API endpoints, which allows to retrieve information about entities stored in database and perform actions with them. The API is organized around REST.
 *
 * API version: 1.0.0
 * Contact: support@qase.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type DefectUpdate struct {
	Title        string                   `json:"title,omitempty"`
	ActualResult string                   `json:"actual_result,omitempty"`
	Severity     int32                    `json:"severity,omitempty"`
	MilestoneId  int32                    `json:"milestone_id,omitempty"`
	Attachments  []string                 `json:"attachments,omitempty"`
	CustomField  *DefectCreateCustomField `json:"custom_field,omitempty"`
	Tags         []string                 `json:"tags,omitempty"`
}
