/*
 * Qase.io API
 *
 * You can use our API to access Qase.io API endpoints, which allows to retrieve information about entities stored in database and perform actions with them. The API is organized around REST.
 *
 * API version: 1.0.0
 * Contact: support@qase.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

import (
	"time"
)

type SharedStep struct {
	Hash           string            `json:"hash,omitempty"`
	Title          string            `json:"title,omitempty"`
	Action         string            `json:"action,omitempty"`
	ExpectedResult string            `json:"expected_result,omitempty"`
	Steps          []SharedStepSteps `json:"steps,omitempty"`
	Data           string            `json:"data,omitempty"`
	Cases          []int32           `json:"cases,omitempty"`
	CasesCount     int32             `json:"cases_count,omitempty"`
	Created        time.Time         `json:"created,omitempty"`
	Updated        time.Time         `json:"updated,omitempty"`
}
