/*
 * Qase.io API
 *
 * You can use our API to access Qase.io API endpoints, which allows to retrieve information about entities stored in database and perform actions with them. The API is organized around REST.
 *
 * API version: 1.0.0
 * Contact: support@qase.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

import (
	"time"
)

type Run struct {
	Id          int32     `json:"id,omitempty"`
	Title       string    `json:"title,omitempty"`
	Description string    `json:"description,omitempty"`
	Status      int32     `json:"status,omitempty"`
	StatusText  string    `json:"status_text,omitempty"`
	StartTime   time.Time `json:"start_time,omitempty"`
	EndTime     time.Time `json:"end_time,omitempty"`
	Public      bool      `json:"public,omitempty"`
	Stats       *RunStats `json:"stats,omitempty"`
	// Time in ms.
	TimeSpent    int32              `json:"time_spent,omitempty"`
	Environment  *RunEnvironment    `json:"environment,omitempty"`
	Milestone    *RunMilestone      `json:"milestone,omitempty"`
	CustomFields []CustomFieldValue `json:"custom_fields,omitempty"`
	Tags         []TagValue         `json:"tags,omitempty"`
	Cases        []int32            `json:"cases,omitempty"`
}
