/*
Qase.io TestOps API v2

Qase TestOps API v2 Specification.

API version: 2.0.0
Contact: support@qase.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_v2_client

import (
	"encoding/json"
)

// checks if the BaseErrorFieldResponseErrorFieldsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseErrorFieldResponseErrorFieldsInner{}

// BaseErrorFieldResponseErrorFieldsInner struct for BaseErrorFieldResponseErrorFieldsInner
type BaseErrorFieldResponseErrorFieldsInner struct {
	Field *string `json:"field,omitempty"`
	Error *string `json:"error,omitempty"`
}

// NewBaseErrorFieldResponseErrorFieldsInner instantiates a new BaseErrorFieldResponseErrorFieldsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseErrorFieldResponseErrorFieldsInner() *BaseErrorFieldResponseErrorFieldsInner {
	this := BaseErrorFieldResponseErrorFieldsInner{}
	return &this
}

// NewBaseErrorFieldResponseErrorFieldsInnerWithDefaults instantiates a new BaseErrorFieldResponseErrorFieldsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseErrorFieldResponseErrorFieldsInnerWithDefaults() *BaseErrorFieldResponseErrorFieldsInner {
	this := BaseErrorFieldResponseErrorFieldsInner{}
	return &this
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *BaseErrorFieldResponseErrorFieldsInner) GetField() string {
	if o == nil || IsNil(o.Field) {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseErrorFieldResponseErrorFieldsInner) GetFieldOk() (*string, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *BaseErrorFieldResponseErrorFieldsInner) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *BaseErrorFieldResponseErrorFieldsInner) SetField(v string) {
	o.Field = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *BaseErrorFieldResponseErrorFieldsInner) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseErrorFieldResponseErrorFieldsInner) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *BaseErrorFieldResponseErrorFieldsInner) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *BaseErrorFieldResponseErrorFieldsInner) SetError(v string) {
	o.Error = &v
}

func (o BaseErrorFieldResponseErrorFieldsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseErrorFieldResponseErrorFieldsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableBaseErrorFieldResponseErrorFieldsInner struct {
	value *BaseErrorFieldResponseErrorFieldsInner
	isSet bool
}

func (v NullableBaseErrorFieldResponseErrorFieldsInner) Get() *BaseErrorFieldResponseErrorFieldsInner {
	return v.value
}

func (v *NullableBaseErrorFieldResponseErrorFieldsInner) Set(val *BaseErrorFieldResponseErrorFieldsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseErrorFieldResponseErrorFieldsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseErrorFieldResponseErrorFieldsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseErrorFieldResponseErrorFieldsInner(val *BaseErrorFieldResponseErrorFieldsInner) *NullableBaseErrorFieldResponseErrorFieldsInner {
	return &NullableBaseErrorFieldResponseErrorFieldsInner{value: val, isSet: true}
}

func (v NullableBaseErrorFieldResponseErrorFieldsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseErrorFieldResponseErrorFieldsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
