/*
Qase.io TestOps API v1

Qase TestOps API v1 Specification.

API version: 1.0.0
Contact: support@qase.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_v1_client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the RunQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunQuery{}

// RunQuery struct for RunQuery
type RunQuery struct {
	Id          *int64         `json:"id,omitempty"`
	RunId       int64          `json:"run_id"`
	Title       *string        `json:"title,omitempty"`
	Description NullableString `json:"description,omitempty"`
	Status      *int32         `json:"status,omitempty"`
	StatusText  *string        `json:"status_text,omitempty"`
	StartTime   NullableTime   `json:"start_time,omitempty"`
	EndTime     NullableTime   `json:"end_time,omitempty"`
	Public      *bool          `json:"public,omitempty"`
	Stats       *RunStats      `json:"stats,omitempty"`
	// Time in ms.
	TimeSpent    *int64                 `json:"time_spent,omitempty"`
	Environment  NullableRunEnvironment `json:"environment,omitempty"`
	Milestone    NullableRunMilestone   `json:"milestone,omitempty"`
	CustomFields []CustomFieldValue     `json:"custom_fields,omitempty"`
	Tags         []TagValue             `json:"tags,omitempty"`
	Cases        []int64                `json:"cases,omitempty"`
	PlanId       NullableInt64          `json:"plan_id,omitempty"`
}

type _RunQuery RunQuery

// NewRunQuery instantiates a new RunQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunQuery(runId int64) *RunQuery {
	this := RunQuery{}
	this.RunId = runId
	return &this
}

// NewRunQueryWithDefaults instantiates a new RunQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunQueryWithDefaults() *RunQuery {
	this := RunQuery{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RunQuery) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunQuery) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RunQuery) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *RunQuery) SetId(v int64) {
	o.Id = &v
}

// GetRunId returns the RunId field value
func (o *RunQuery) GetRunId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RunId
}

// GetRunIdOk returns a tuple with the RunId field value
// and a boolean to check if the value has been set.
func (o *RunQuery) GetRunIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RunId, true
}

// SetRunId sets field value
func (o *RunQuery) SetRunId(v int64) {
	o.RunId = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *RunQuery) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunQuery) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *RunQuery) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *RunQuery) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RunQuery) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RunQuery) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *RunQuery) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *RunQuery) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *RunQuery) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *RunQuery) UnsetDescription() {
	o.Description.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RunQuery) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunQuery) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RunQuery) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *RunQuery) SetStatus(v int32) {
	o.Status = &v
}

// GetStatusText returns the StatusText field value if set, zero value otherwise.
func (o *RunQuery) GetStatusText() string {
	if o == nil || IsNil(o.StatusText) {
		var ret string
		return ret
	}
	return *o.StatusText
}

// GetStatusTextOk returns a tuple with the StatusText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunQuery) GetStatusTextOk() (*string, bool) {
	if o == nil || IsNil(o.StatusText) {
		return nil, false
	}
	return o.StatusText, true
}

// HasStatusText returns a boolean if a field has been set.
func (o *RunQuery) HasStatusText() bool {
	if o != nil && !IsNil(o.StatusText) {
		return true
	}

	return false
}

// SetStatusText gets a reference to the given string and assigns it to the StatusText field.
func (o *RunQuery) SetStatusText(v string) {
	o.StatusText = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RunQuery) GetStartTime() time.Time {
	if o == nil || IsNil(o.StartTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartTime.Get()
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RunQuery) GetStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartTime.Get(), o.StartTime.IsSet()
}

// HasStartTime returns a boolean if a field has been set.
func (o *RunQuery) HasStartTime() bool {
	if o != nil && o.StartTime.IsSet() {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given NullableTime and assigns it to the StartTime field.
func (o *RunQuery) SetStartTime(v time.Time) {
	o.StartTime.Set(&v)
}

// SetStartTimeNil sets the value for StartTime to be an explicit nil
func (o *RunQuery) SetStartTimeNil() {
	o.StartTime.Set(nil)
}

// UnsetStartTime ensures that no value is present for StartTime, not even an explicit nil
func (o *RunQuery) UnsetStartTime() {
	o.StartTime.Unset()
}

// GetEndTime returns the EndTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RunQuery) GetEndTime() time.Time {
	if o == nil || IsNil(o.EndTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndTime.Get()
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RunQuery) GetEndTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndTime.Get(), o.EndTime.IsSet()
}

// HasEndTime returns a boolean if a field has been set.
func (o *RunQuery) HasEndTime() bool {
	if o != nil && o.EndTime.IsSet() {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given NullableTime and assigns it to the EndTime field.
func (o *RunQuery) SetEndTime(v time.Time) {
	o.EndTime.Set(&v)
}

// SetEndTimeNil sets the value for EndTime to be an explicit nil
func (o *RunQuery) SetEndTimeNil() {
	o.EndTime.Set(nil)
}

// UnsetEndTime ensures that no value is present for EndTime, not even an explicit nil
func (o *RunQuery) UnsetEndTime() {
	o.EndTime.Unset()
}

// GetPublic returns the Public field value if set, zero value otherwise.
func (o *RunQuery) GetPublic() bool {
	if o == nil || IsNil(o.Public) {
		var ret bool
		return ret
	}
	return *o.Public
}

// GetPublicOk returns a tuple with the Public field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunQuery) GetPublicOk() (*bool, bool) {
	if o == nil || IsNil(o.Public) {
		return nil, false
	}
	return o.Public, true
}

// HasPublic returns a boolean if a field has been set.
func (o *RunQuery) HasPublic() bool {
	if o != nil && !IsNil(o.Public) {
		return true
	}

	return false
}

// SetPublic gets a reference to the given bool and assigns it to the Public field.
func (o *RunQuery) SetPublic(v bool) {
	o.Public = &v
}

// GetStats returns the Stats field value if set, zero value otherwise.
func (o *RunQuery) GetStats() RunStats {
	if o == nil || IsNil(o.Stats) {
		var ret RunStats
		return ret
	}
	return *o.Stats
}

// GetStatsOk returns a tuple with the Stats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunQuery) GetStatsOk() (*RunStats, bool) {
	if o == nil || IsNil(o.Stats) {
		return nil, false
	}
	return o.Stats, true
}

// HasStats returns a boolean if a field has been set.
func (o *RunQuery) HasStats() bool {
	if o != nil && !IsNil(o.Stats) {
		return true
	}

	return false
}

// SetStats gets a reference to the given RunStats and assigns it to the Stats field.
func (o *RunQuery) SetStats(v RunStats) {
	o.Stats = &v
}

// GetTimeSpent returns the TimeSpent field value if set, zero value otherwise.
func (o *RunQuery) GetTimeSpent() int64 {
	if o == nil || IsNil(o.TimeSpent) {
		var ret int64
		return ret
	}
	return *o.TimeSpent
}

// GetTimeSpentOk returns a tuple with the TimeSpent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunQuery) GetTimeSpentOk() (*int64, bool) {
	if o == nil || IsNil(o.TimeSpent) {
		return nil, false
	}
	return o.TimeSpent, true
}

// HasTimeSpent returns a boolean if a field has been set.
func (o *RunQuery) HasTimeSpent() bool {
	if o != nil && !IsNil(o.TimeSpent) {
		return true
	}

	return false
}

// SetTimeSpent gets a reference to the given int64 and assigns it to the TimeSpent field.
func (o *RunQuery) SetTimeSpent(v int64) {
	o.TimeSpent = &v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RunQuery) GetEnvironment() RunEnvironment {
	if o == nil || IsNil(o.Environment.Get()) {
		var ret RunEnvironment
		return ret
	}
	return *o.Environment.Get()
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RunQuery) GetEnvironmentOk() (*RunEnvironment, bool) {
	if o == nil {
		return nil, false
	}
	return o.Environment.Get(), o.Environment.IsSet()
}

// HasEnvironment returns a boolean if a field has been set.
func (o *RunQuery) HasEnvironment() bool {
	if o != nil && o.Environment.IsSet() {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given NullableRunEnvironment and assigns it to the Environment field.
func (o *RunQuery) SetEnvironment(v RunEnvironment) {
	o.Environment.Set(&v)
}

// SetEnvironmentNil sets the value for Environment to be an explicit nil
func (o *RunQuery) SetEnvironmentNil() {
	o.Environment.Set(nil)
}

// UnsetEnvironment ensures that no value is present for Environment, not even an explicit nil
func (o *RunQuery) UnsetEnvironment() {
	o.Environment.Unset()
}

// GetMilestone returns the Milestone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RunQuery) GetMilestone() RunMilestone {
	if o == nil || IsNil(o.Milestone.Get()) {
		var ret RunMilestone
		return ret
	}
	return *o.Milestone.Get()
}

// GetMilestoneOk returns a tuple with the Milestone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RunQuery) GetMilestoneOk() (*RunMilestone, bool) {
	if o == nil {
		return nil, false
	}
	return o.Milestone.Get(), o.Milestone.IsSet()
}

// HasMilestone returns a boolean if a field has been set.
func (o *RunQuery) HasMilestone() bool {
	if o != nil && o.Milestone.IsSet() {
		return true
	}

	return false
}

// SetMilestone gets a reference to the given NullableRunMilestone and assigns it to the Milestone field.
func (o *RunQuery) SetMilestone(v RunMilestone) {
	o.Milestone.Set(&v)
}

// SetMilestoneNil sets the value for Milestone to be an explicit nil
func (o *RunQuery) SetMilestoneNil() {
	o.Milestone.Set(nil)
}

// UnsetMilestone ensures that no value is present for Milestone, not even an explicit nil
func (o *RunQuery) UnsetMilestone() {
	o.Milestone.Unset()
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *RunQuery) GetCustomFields() []CustomFieldValue {
	if o == nil || IsNil(o.CustomFields) {
		var ret []CustomFieldValue
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunQuery) GetCustomFieldsOk() ([]CustomFieldValue, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return nil, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *RunQuery) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given []CustomFieldValue and assigns it to the CustomFields field.
func (o *RunQuery) SetCustomFields(v []CustomFieldValue) {
	o.CustomFields = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *RunQuery) GetTags() []TagValue {
	if o == nil || IsNil(o.Tags) {
		var ret []TagValue
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunQuery) GetTagsOk() ([]TagValue, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *RunQuery) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []TagValue and assigns it to the Tags field.
func (o *RunQuery) SetTags(v []TagValue) {
	o.Tags = v
}

// GetCases returns the Cases field value if set, zero value otherwise.
func (o *RunQuery) GetCases() []int64 {
	if o == nil || IsNil(o.Cases) {
		var ret []int64
		return ret
	}
	return o.Cases
}

// GetCasesOk returns a tuple with the Cases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunQuery) GetCasesOk() ([]int64, bool) {
	if o == nil || IsNil(o.Cases) {
		return nil, false
	}
	return o.Cases, true
}

// HasCases returns a boolean if a field has been set.
func (o *RunQuery) HasCases() bool {
	if o != nil && !IsNil(o.Cases) {
		return true
	}

	return false
}

// SetCases gets a reference to the given []int64 and assigns it to the Cases field.
func (o *RunQuery) SetCases(v []int64) {
	o.Cases = v
}

// GetPlanId returns the PlanId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RunQuery) GetPlanId() int64 {
	if o == nil || IsNil(o.PlanId.Get()) {
		var ret int64
		return ret
	}
	return *o.PlanId.Get()
}

// GetPlanIdOk returns a tuple with the PlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RunQuery) GetPlanIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlanId.Get(), o.PlanId.IsSet()
}

// HasPlanId returns a boolean if a field has been set.
func (o *RunQuery) HasPlanId() bool {
	if o != nil && o.PlanId.IsSet() {
		return true
	}

	return false
}

// SetPlanId gets a reference to the given NullableInt64 and assigns it to the PlanId field.
func (o *RunQuery) SetPlanId(v int64) {
	o.PlanId.Set(&v)
}

// SetPlanIdNil sets the value for PlanId to be an explicit nil
func (o *RunQuery) SetPlanIdNil() {
	o.PlanId.Set(nil)
}

// UnsetPlanId ensures that no value is present for PlanId, not even an explicit nil
func (o *RunQuery) UnsetPlanId() {
	o.PlanId.Unset()
}

func (o RunQuery) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["run_id"] = o.RunId
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusText) {
		toSerialize["status_text"] = o.StatusText
	}
	if o.StartTime.IsSet() {
		toSerialize["start_time"] = o.StartTime.Get()
	}
	if o.EndTime.IsSet() {
		toSerialize["end_time"] = o.EndTime.Get()
	}
	if !IsNil(o.Public) {
		toSerialize["public"] = o.Public
	}
	if !IsNil(o.Stats) {
		toSerialize["stats"] = o.Stats
	}
	if !IsNil(o.TimeSpent) {
		toSerialize["time_spent"] = o.TimeSpent
	}
	if o.Environment.IsSet() {
		toSerialize["environment"] = o.Environment.Get()
	}
	if o.Milestone.IsSet() {
		toSerialize["milestone"] = o.Milestone.Get()
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Cases) {
		toSerialize["cases"] = o.Cases
	}
	if o.PlanId.IsSet() {
		toSerialize["plan_id"] = o.PlanId.Get()
	}
	return toSerialize, nil
}

func (o *RunQuery) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"run_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRunQuery := _RunQuery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRunQuery)

	if err != nil {
		return err
	}

	*o = RunQuery(varRunQuery)

	return err
}

type NullableRunQuery struct {
	value *RunQuery
	isSet bool
}

func (v NullableRunQuery) Get() *RunQuery {
	return v.value
}

func (v *NullableRunQuery) Set(val *RunQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableRunQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableRunQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunQuery(val *RunQuery) *NullableRunQuery {
	return &NullableRunQuery{value: val, isSet: true}
}

func (v NullableRunQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
