/*
Qase.io TestOps API v1

Qase TestOps API v1 Specification.

API version: 1.0.0
Contact: support@qase.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_v1_client

import (
	"encoding/json"
)

// checks if the DefectListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefectListResponse{}

// DefectListResponse struct for DefectListResponse
type DefectListResponse struct {
	Status *bool                          `json:"status,omitempty"`
	Result *DefectListResponseAllOfResult `json:"result,omitempty"`
}

// NewDefectListResponse instantiates a new DefectListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefectListResponse() *DefectListResponse {
	this := DefectListResponse{}
	return &this
}

// NewDefectListResponseWithDefaults instantiates a new DefectListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefectListResponseWithDefaults() *DefectListResponse {
	this := DefectListResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DefectListResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefectListResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DefectListResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *DefectListResponse) SetStatus(v bool) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *DefectListResponse) GetResult() DefectListResponseAllOfResult {
	if o == nil || IsNil(o.Result) {
		var ret DefectListResponseAllOfResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefectListResponse) GetResultOk() (*DefectListResponseAllOfResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *DefectListResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given DefectListResponseAllOfResult and assigns it to the Result field.
func (o *DefectListResponse) SetResult(v DefectListResponseAllOfResult) {
	o.Result = &v
}

func (o DefectListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefectListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableDefectListResponse struct {
	value *DefectListResponse
	isSet bool
}

func (v NullableDefectListResponse) Get() *DefectListResponse {
	return v.value
}

func (v *NullableDefectListResponse) Set(val *DefectListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDefectListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDefectListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefectListResponse(val *DefectListResponse) *NullableDefectListResponse {
	return &NullableDefectListResponse{value: val, isSet: true}
}

func (v NullableDefectListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefectListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
