/*
Qase.io TestOps API v1

Qase TestOps API v1 Specification.

API version: 1.0.0
Contact: support@qase.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_v1_client

import (
	"encoding/json"
)

// checks if the RunListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunListResponse{}

// RunListResponse struct for RunListResponse
type RunListResponse struct {
	Status *bool                       `json:"status,omitempty"`
	Result *RunListResponseAllOfResult `json:"result,omitempty"`
}

// NewRunListResponse instantiates a new RunListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunListResponse() *RunListResponse {
	this := RunListResponse{}
	return &this
}

// NewRunListResponseWithDefaults instantiates a new RunListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunListResponseWithDefaults() *RunListResponse {
	this := RunListResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RunListResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunListResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RunListResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *RunListResponse) SetStatus(v bool) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *RunListResponse) GetResult() RunListResponseAllOfResult {
	if o == nil || IsNil(o.Result) {
		var ret RunListResponseAllOfResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunListResponse) GetResultOk() (*RunListResponseAllOfResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *RunListResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given RunListResponseAllOfResult and assigns it to the Result field.
func (o *RunListResponse) SetResult(v RunListResponseAllOfResult) {
	o.Result = &v
}

func (o RunListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableRunListResponse struct {
	value *RunListResponse
	isSet bool
}

func (v NullableRunListResponse) Get() *RunListResponse {
	return v.value
}

func (v *NullableRunListResponse) Set(val *RunListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRunListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRunListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunListResponse(val *RunListResponse) *NullableRunListResponse {
	return &NullableRunListResponse{value: val, isSet: true}
}

func (v NullableRunListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
