/*
Qase.io TestOps API v1

Qase TestOps API v1 Specification.

API version: 1.0.0
Contact: support@qase.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_v1_client

import (
	"encoding/json"
)

// checks if the Bulk200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Bulk200Response{}

// Bulk200Response struct for Bulk200Response
type Bulk200Response struct {
	Status *bool                       `json:"status,omitempty"`
	Result *Bulk200ResponseAllOfResult `json:"result,omitempty"`
}

// NewBulk200Response instantiates a new Bulk200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulk200Response() *Bulk200Response {
	this := Bulk200Response{}
	return &this
}

// NewBulk200ResponseWithDefaults instantiates a new Bulk200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulk200ResponseWithDefaults() *Bulk200Response {
	this := Bulk200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Bulk200Response) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bulk200Response) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Bulk200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *Bulk200Response) SetStatus(v bool) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *Bulk200Response) GetResult() Bulk200ResponseAllOfResult {
	if o == nil || IsNil(o.Result) {
		var ret Bulk200ResponseAllOfResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bulk200Response) GetResultOk() (*Bulk200ResponseAllOfResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *Bulk200Response) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given Bulk200ResponseAllOfResult and assigns it to the Result field.
func (o *Bulk200Response) SetResult(v Bulk200ResponseAllOfResult) {
	o.Result = &v
}

func (o Bulk200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Bulk200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableBulk200Response struct {
	value *Bulk200Response
	isSet bool
}

func (v NullableBulk200Response) Get() *Bulk200Response {
	return v.value
}

func (v *NullableBulk200Response) Set(val *Bulk200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableBulk200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableBulk200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulk200Response(val *Bulk200Response) *NullableBulk200Response {
	return &NullableBulk200Response{value: val, isSet: true}
}

func (v NullableBulk200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulk200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
