/*
Qase.io TestOps API v1

Qase TestOps API v1 Specification.

API version: 1.0.0
Contact: support@qase.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_v1_client

import (
	"encoding/json"
)

// checks if the RunPublicResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunPublicResponse{}

// RunPublicResponse struct for RunPublicResponse
type RunPublicResponse struct {
	Status *bool                         `json:"status,omitempty"`
	Result *RunPublicResponseAllOfResult `json:"result,omitempty"`
}

// NewRunPublicResponse instantiates a new RunPublicResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunPublicResponse() *RunPublicResponse {
	this := RunPublicResponse{}
	return &this
}

// NewRunPublicResponseWithDefaults instantiates a new RunPublicResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunPublicResponseWithDefaults() *RunPublicResponse {
	this := RunPublicResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RunPublicResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunPublicResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RunPublicResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *RunPublicResponse) SetStatus(v bool) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *RunPublicResponse) GetResult() RunPublicResponseAllOfResult {
	if o == nil || IsNil(o.Result) {
		var ret RunPublicResponseAllOfResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunPublicResponse) GetResultOk() (*RunPublicResponseAllOfResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *RunPublicResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given RunPublicResponseAllOfResult and assigns it to the Result field.
func (o *RunPublicResponse) SetResult(v RunPublicResponseAllOfResult) {
	o.Result = &v
}

func (o RunPublicResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunPublicResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableRunPublicResponse struct {
	value *RunPublicResponse
	isSet bool
}

func (v NullableRunPublicResponse) Get() *RunPublicResponse {
	return v.value
}

func (v *NullableRunPublicResponse) Set(val *RunPublicResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRunPublicResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRunPublicResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunPublicResponse(val *RunPublicResponse) *NullableRunPublicResponse {
	return &NullableRunPublicResponse{value: val, isSet: true}
}

func (v NullableRunPublicResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunPublicResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
