/*
Qase.io TestOps API v1

Qase TestOps API v1 Specification.

API version: 1.0.0
Contact: support@qase.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_v1_client

import (
	"encoding/json"
)

// checks if the ReviewBulkResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReviewBulkResponse{}

// ReviewBulkResponse struct for ReviewBulkResponse
type ReviewBulkResponse struct {
	Status *bool                          `json:"status,omitempty"`
	Result *ReviewBulkResponseAllOfResult `json:"result,omitempty"`
}

// NewReviewBulkResponse instantiates a new ReviewBulkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReviewBulkResponse() *ReviewBulkResponse {
	this := ReviewBulkResponse{}
	return &this
}

// NewReviewBulkResponseWithDefaults instantiates a new ReviewBulkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReviewBulkResponseWithDefaults() *ReviewBulkResponse {
	this := ReviewBulkResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ReviewBulkResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewBulkResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ReviewBulkResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *ReviewBulkResponse) SetStatus(v bool) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *ReviewBulkResponse) GetResult() ReviewBulkResponseAllOfResult {
	if o == nil || IsNil(o.Result) {
		var ret ReviewBulkResponseAllOfResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewBulkResponse) GetResultOk() (*ReviewBulkResponseAllOfResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *ReviewBulkResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given ReviewBulkResponseAllOfResult and assigns it to the Result field.
func (o *ReviewBulkResponse) SetResult(v ReviewBulkResponseAllOfResult) {
	o.Result = &v
}

func (o ReviewBulkResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReviewBulkResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableReviewBulkResponse struct {
	value *ReviewBulkResponse
	isSet bool
}

func (v NullableReviewBulkResponse) Get() *ReviewBulkResponse {
	return v.value
}

func (v *NullableReviewBulkResponse) Set(val *ReviewBulkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReviewBulkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReviewBulkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReviewBulkResponse(val *ReviewBulkResponse) *NullableReviewBulkResponse {
	return &NullableReviewBulkResponse{value: val, isSet: true}
}

func (v NullableReviewBulkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReviewBulkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
