/*
Qase.io TestOps API v1

Qase TestOps API v1 Specification.

API version: 1.0.0
Contact: support@qase.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_v1_client

import (
	"encoding/json"
)

// checks if the TestCaseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TestCaseResponse{}

// TestCaseResponse struct for TestCaseResponse
type TestCaseResponse struct {
	Status *bool     `json:"status,omitempty"`
	Result *TestCase `json:"result,omitempty"`
}

// NewTestCaseResponse instantiates a new TestCaseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestCaseResponse() *TestCaseResponse {
	this := TestCaseResponse{}
	return &this
}

// NewTestCaseResponseWithDefaults instantiates a new TestCaseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestCaseResponseWithDefaults() *TestCaseResponse {
	this := TestCaseResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TestCaseResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestCaseResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TestCaseResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *TestCaseResponse) SetStatus(v bool) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *TestCaseResponse) GetResult() TestCase {
	if o == nil || IsNil(o.Result) {
		var ret TestCase
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestCaseResponse) GetResultOk() (*TestCase, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *TestCaseResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given TestCase and assigns it to the Result field.
func (o *TestCaseResponse) SetResult(v TestCase) {
	o.Result = &v
}

func (o TestCaseResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TestCaseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableTestCaseResponse struct {
	value *TestCaseResponse
	isSet bool
}

func (v NullableTestCaseResponse) Get() *TestCaseResponse {
	return v.value
}

func (v *NullableTestCaseResponse) Set(val *TestCaseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTestCaseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTestCaseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestCaseResponse(val *TestCaseResponse) *NullableTestCaseResponse {
	return &NullableTestCaseResponse{value: val, isSet: true}
}

func (v NullableTestCaseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestCaseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
