/*
Qase.io TestOps API v1

Qase TestOps API v1 Specification.

API version: 1.0.0
Contact: support@qase.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_v1_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RunPublic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunPublic{}

// RunPublic struct for RunPublic
type RunPublic struct {
	Status bool `json:"status"`
}

type _RunPublic RunPublic

// NewRunPublic instantiates a new RunPublic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunPublic(status bool) *RunPublic {
	this := RunPublic{}
	this.Status = status
	return &this
}

// NewRunPublicWithDefaults instantiates a new RunPublic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunPublicWithDefaults() *RunPublic {
	this := RunPublic{}
	return &this
}

// GetStatus returns the Status field value
func (o *RunPublic) GetStatus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *RunPublic) GetStatusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *RunPublic) SetStatus(v bool) {
	o.Status = v
}

func (o RunPublic) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunPublic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *RunPublic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRunPublic := _RunPublic{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRunPublic)

	if err != nil {
		return err
	}

	*o = RunPublic(varRunPublic)

	return err
}

type NullableRunPublic struct {
	value *RunPublic
	isSet bool
}

func (v NullableRunPublic) Get() *RunPublic {
	return v.value
}

func (v *NullableRunPublic) Set(val *RunPublic) {
	v.value = val
	v.isSet = true
}

func (v NullableRunPublic) IsSet() bool {
	return v.isSet
}

func (v *NullableRunPublic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunPublic(val *RunPublic) *NullableRunPublic {
	return &NullableRunPublic{value: val, isSet: true}
}

func (v NullableRunPublic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunPublic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
