/*
Qase.io TestOps API v1

Qase TestOps API v1 Specification.

API version: 1.0.0
Contact: support@qase.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_v1_client

import (
	"encoding/json"
)

// checks if the PlanResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlanResponse{}

// PlanResponse struct for PlanResponse
type PlanResponse struct {
	Status *bool         `json:"status,omitempty"`
	Result *PlanDetailed `json:"result,omitempty"`
}

// NewPlanResponse instantiates a new PlanResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanResponse() *PlanResponse {
	this := PlanResponse{}
	return &this
}

// NewPlanResponseWithDefaults instantiates a new PlanResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanResponseWithDefaults() *PlanResponse {
	this := PlanResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PlanResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PlanResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *PlanResponse) SetStatus(v bool) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *PlanResponse) GetResult() PlanDetailed {
	if o == nil || IsNil(o.Result) {
		var ret PlanDetailed
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanResponse) GetResultOk() (*PlanDetailed, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *PlanResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given PlanDetailed and assigns it to the Result field.
func (o *PlanResponse) SetResult(v PlanDetailed) {
	o.Result = &v
}

func (o PlanResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlanResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullablePlanResponse struct {
	value *PlanResponse
	isSet bool
}

func (v NullablePlanResponse) Get() *PlanResponse {
	return v.value
}

func (v *NullablePlanResponse) Set(val *PlanResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanResponse(val *PlanResponse) *NullablePlanResponse {
	return &NullablePlanResponse{value: val, isSet: true}
}

func (v NullablePlanResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
