/*
Qase.io TestOps API v1

Qase TestOps API v1 Specification.

API version: 1.0.0
Contact: support@qase.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_v1_client

import (
	"encoding/json"
)

// checks if the ReviewUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReviewUpdate{}

// ReviewUpdate struct for ReviewUpdate
type ReviewUpdate struct {
	// Author UUIDs of team members assigned as reviewers (see `GET /author`). When provided, replaces the current reviewer list; an empty array removes all reviewers. Omit to leave reviewers unchanged.
	Reviewers []string `json:"reviewers,omitempty"`
	// Sent fields are merged into the stored proposal. Changing the proposal resets all existing approvals; updating only the reviewers keeps them.
	ProposedCase *ReviewCaseData `json:"proposed_case,omitempty"`
}

// NewReviewUpdate instantiates a new ReviewUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReviewUpdate() *ReviewUpdate {
	this := ReviewUpdate{}
	return &this
}

// NewReviewUpdateWithDefaults instantiates a new ReviewUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReviewUpdateWithDefaults() *ReviewUpdate {
	this := ReviewUpdate{}
	return &this
}

// GetReviewers returns the Reviewers field value if set, zero value otherwise.
func (o *ReviewUpdate) GetReviewers() []string {
	if o == nil || IsNil(o.Reviewers) {
		var ret []string
		return ret
	}
	return o.Reviewers
}

// GetReviewersOk returns a tuple with the Reviewers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewUpdate) GetReviewersOk() ([]string, bool) {
	if o == nil || IsNil(o.Reviewers) {
		return nil, false
	}
	return o.Reviewers, true
}

// HasReviewers returns a boolean if a field has been set.
func (o *ReviewUpdate) HasReviewers() bool {
	if o != nil && !IsNil(o.Reviewers) {
		return true
	}

	return false
}

// SetReviewers gets a reference to the given []string and assigns it to the Reviewers field.
func (o *ReviewUpdate) SetReviewers(v []string) {
	o.Reviewers = v
}

// GetProposedCase returns the ProposedCase field value if set, zero value otherwise.
func (o *ReviewUpdate) GetProposedCase() ReviewCaseData {
	if o == nil || IsNil(o.ProposedCase) {
		var ret ReviewCaseData
		return ret
	}
	return *o.ProposedCase
}

// GetProposedCaseOk returns a tuple with the ProposedCase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewUpdate) GetProposedCaseOk() (*ReviewCaseData, bool) {
	if o == nil || IsNil(o.ProposedCase) {
		return nil, false
	}
	return o.ProposedCase, true
}

// HasProposedCase returns a boolean if a field has been set.
func (o *ReviewUpdate) HasProposedCase() bool {
	if o != nil && !IsNil(o.ProposedCase) {
		return true
	}

	return false
}

// SetProposedCase gets a reference to the given ReviewCaseData and assigns it to the ProposedCase field.
func (o *ReviewUpdate) SetProposedCase(v ReviewCaseData) {
	o.ProposedCase = &v
}

func (o ReviewUpdate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReviewUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Reviewers) {
		toSerialize["reviewers"] = o.Reviewers
	}
	if !IsNil(o.ProposedCase) {
		toSerialize["proposed_case"] = o.ProposedCase
	}
	return toSerialize, nil
}

type NullableReviewUpdate struct {
	value *ReviewUpdate
	isSet bool
}

func (v NullableReviewUpdate) Get() *ReviewUpdate {
	return v.value
}

func (v *NullableReviewUpdate) Set(val *ReviewUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableReviewUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableReviewUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReviewUpdate(val *ReviewUpdate) *NullableReviewUpdate {
	return &NullableReviewUpdate{value: val, isSet: true}
}

func (v NullableReviewUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReviewUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
