/*
Qase.io TestOps API v1

Qase TestOps API v1 Specification.

API version: 1.0.0
Contact: support@qase.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_v1_client

import (
	"encoding/json"
)

// checks if the ReviewListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReviewListResponse{}

// ReviewListResponse struct for ReviewListResponse
type ReviewListResponse struct {
	Status *bool                          `json:"status,omitempty"`
	Result *ReviewListResponseAllOfResult `json:"result,omitempty"`
}

// NewReviewListResponse instantiates a new ReviewListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReviewListResponse() *ReviewListResponse {
	this := ReviewListResponse{}
	return &this
}

// NewReviewListResponseWithDefaults instantiates a new ReviewListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReviewListResponseWithDefaults() *ReviewListResponse {
	this := ReviewListResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ReviewListResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewListResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ReviewListResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *ReviewListResponse) SetStatus(v bool) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *ReviewListResponse) GetResult() ReviewListResponseAllOfResult {
	if o == nil || IsNil(o.Result) {
		var ret ReviewListResponseAllOfResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewListResponse) GetResultOk() (*ReviewListResponseAllOfResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *ReviewListResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given ReviewListResponseAllOfResult and assigns it to the Result field.
func (o *ReviewListResponse) SetResult(v ReviewListResponseAllOfResult) {
	o.Result = &v
}

func (o ReviewListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReviewListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableReviewListResponse struct {
	value *ReviewListResponse
	isSet bool
}

func (v NullableReviewListResponse) Get() *ReviewListResponse {
	return v.value
}

func (v *NullableReviewListResponse) Set(val *ReviewListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReviewListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReviewListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReviewListResponse(val *ReviewListResponse) *NullableReviewListResponse {
	return &NullableReviewListResponse{value: val, isSet: true}
}

func (v NullableReviewListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReviewListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
