/*
Qase.io TestOps API v1

Qase TestOps API v1 Specification.

API version: 1.0.0
Contact: support@qase.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_v1_client

import (
	"encoding/json"
)

// checks if the IdResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdResponse{}

// IdResponse struct for IdResponse
type IdResponse struct {
	Status *bool                  `json:"status,omitempty"`
	Result *IdResponseAllOfResult `json:"result,omitempty"`
}

// NewIdResponse instantiates a new IdResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdResponse() *IdResponse {
	this := IdResponse{}
	return &this
}

// NewIdResponseWithDefaults instantiates a new IdResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdResponseWithDefaults() *IdResponse {
	this := IdResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *IdResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *IdResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *IdResponse) SetStatus(v bool) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *IdResponse) GetResult() IdResponseAllOfResult {
	if o == nil || IsNil(o.Result) {
		var ret IdResponseAllOfResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdResponse) GetResultOk() (*IdResponseAllOfResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *IdResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given IdResponseAllOfResult and assigns it to the Result field.
func (o *IdResponse) SetResult(v IdResponseAllOfResult) {
	o.Result = &v
}

func (o IdResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableIdResponse struct {
	value *IdResponse
	isSet bool
}

func (v NullableIdResponse) Get() *IdResponse {
	return v.value
}

func (v *NullableIdResponse) Set(val *IdResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIdResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIdResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdResponse(val *IdResponse) *NullableIdResponse {
	return &NullableIdResponse{value: val, isSet: true}
}

func (v NullableIdResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
