/*
Qase.io TestOps API v1

Qase TestOps API v1 Specification.

API version: 1.0.0
Contact: support@qase.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_v1_client

import (
	"encoding/json"
)

// checks if the ReviewCaseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReviewCaseData{}

// ReviewCaseData The test case fields proposed by the review.
type ReviewCaseData struct {
	Title          *string        `json:"title,omitempty"`
	Description    NullableString `json:"description,omitempty"`
	Preconditions  NullableString `json:"preconditions,omitempty"`
	Postconditions NullableString `json:"postconditions,omitempty"`
	Severity       NullableInt32  `json:"severity,omitempty"`
	Priority       NullableInt32  `json:"priority,omitempty"`
	Behavior       NullableInt32  `json:"behavior,omitempty"`
	Type           NullableInt32  `json:"type,omitempty"`
	Layer          NullableInt32  `json:"layer,omitempty"`
	IsFlaky        NullableInt32  `json:"is_flaky,omitempty"`
	// Mute state of the proposed test case.
	IsMuted     *bool         `json:"is_muted,omitempty"`
	SuiteId     NullableInt64 `json:"suite_id,omitempty"`
	MilestoneId NullableInt64 `json:"milestone_id,omitempty"`
	// `true` if the case is manual, `false` if it is automated.
	IsManual *bool `json:"is_manual,omitempty"`
	// `true` if a manual case is planned to be automated.
	IsToBeAutomated *bool         `json:"is_to_be_automated,omitempty"`
	Status          NullableInt32 `json:"status,omitempty"`
	// Format of the steps field. Omit to keep the current one, `classic` for a new-case draft; changing it requires sending `steps` in the same request.
	StepsType *string `json:"steps_type,omitempty"`
	// A list of Attachment hashes.
	Attachments []string `json:"attachments,omitempty"`
	// For gherkin steps send the scenario in `value`.
	Steps      []ReviewStepData          `json:"steps,omitempty"`
	Tags       []string                  `json:"tags,omitempty"`
	Parameters []TestCaseParameterCreate `json:"parameters,omitempty"`
	// Map of custom field ID to value. A `create` review must carry every required custom field. An `edit` review is validated against the current test case, so send only the fields the proposal changes.
	CustomField *map[string]string `json:"custom_field,omitempty"`
}

// NewReviewCaseData instantiates a new ReviewCaseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReviewCaseData() *ReviewCaseData {
	this := ReviewCaseData{}
	return &this
}

// NewReviewCaseDataWithDefaults instantiates a new ReviewCaseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReviewCaseDataWithDefaults() *ReviewCaseData {
	this := ReviewCaseData{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ReviewCaseData) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewCaseData) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ReviewCaseData) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ReviewCaseData) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReviewCaseData) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReviewCaseData) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ReviewCaseData) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ReviewCaseData) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ReviewCaseData) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ReviewCaseData) UnsetDescription() {
	o.Description.Unset()
}

// GetPreconditions returns the Preconditions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReviewCaseData) GetPreconditions() string {
	if o == nil || IsNil(o.Preconditions.Get()) {
		var ret string
		return ret
	}
	return *o.Preconditions.Get()
}

// GetPreconditionsOk returns a tuple with the Preconditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReviewCaseData) GetPreconditionsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Preconditions.Get(), o.Preconditions.IsSet()
}

// HasPreconditions returns a boolean if a field has been set.
func (o *ReviewCaseData) HasPreconditions() bool {
	if o != nil && o.Preconditions.IsSet() {
		return true
	}

	return false
}

// SetPreconditions gets a reference to the given NullableString and assigns it to the Preconditions field.
func (o *ReviewCaseData) SetPreconditions(v string) {
	o.Preconditions.Set(&v)
}

// SetPreconditionsNil sets the value for Preconditions to be an explicit nil
func (o *ReviewCaseData) SetPreconditionsNil() {
	o.Preconditions.Set(nil)
}

// UnsetPreconditions ensures that no value is present for Preconditions, not even an explicit nil
func (o *ReviewCaseData) UnsetPreconditions() {
	o.Preconditions.Unset()
}

// GetPostconditions returns the Postconditions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReviewCaseData) GetPostconditions() string {
	if o == nil || IsNil(o.Postconditions.Get()) {
		var ret string
		return ret
	}
	return *o.Postconditions.Get()
}

// GetPostconditionsOk returns a tuple with the Postconditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReviewCaseData) GetPostconditionsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Postconditions.Get(), o.Postconditions.IsSet()
}

// HasPostconditions returns a boolean if a field has been set.
func (o *ReviewCaseData) HasPostconditions() bool {
	if o != nil && o.Postconditions.IsSet() {
		return true
	}

	return false
}

// SetPostconditions gets a reference to the given NullableString and assigns it to the Postconditions field.
func (o *ReviewCaseData) SetPostconditions(v string) {
	o.Postconditions.Set(&v)
}

// SetPostconditionsNil sets the value for Postconditions to be an explicit nil
func (o *ReviewCaseData) SetPostconditionsNil() {
	o.Postconditions.Set(nil)
}

// UnsetPostconditions ensures that no value is present for Postconditions, not even an explicit nil
func (o *ReviewCaseData) UnsetPostconditions() {
	o.Postconditions.Unset()
}

// GetSeverity returns the Severity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReviewCaseData) GetSeverity() int32 {
	if o == nil || IsNil(o.Severity.Get()) {
		var ret int32
		return ret
	}
	return *o.Severity.Get()
}

// GetSeverityOk returns a tuple with the Severity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReviewCaseData) GetSeverityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Severity.Get(), o.Severity.IsSet()
}

// HasSeverity returns a boolean if a field has been set.
func (o *ReviewCaseData) HasSeverity() bool {
	if o != nil && o.Severity.IsSet() {
		return true
	}

	return false
}

// SetSeverity gets a reference to the given NullableInt32 and assigns it to the Severity field.
func (o *ReviewCaseData) SetSeverity(v int32) {
	o.Severity.Set(&v)
}

// SetSeverityNil sets the value for Severity to be an explicit nil
func (o *ReviewCaseData) SetSeverityNil() {
	o.Severity.Set(nil)
}

// UnsetSeverity ensures that no value is present for Severity, not even an explicit nil
func (o *ReviewCaseData) UnsetSeverity() {
	o.Severity.Unset()
}

// GetPriority returns the Priority field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReviewCaseData) GetPriority() int32 {
	if o == nil || IsNil(o.Priority.Get()) {
		var ret int32
		return ret
	}
	return *o.Priority.Get()
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReviewCaseData) GetPriorityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Priority.Get(), o.Priority.IsSet()
}

// HasPriority returns a boolean if a field has been set.
func (o *ReviewCaseData) HasPriority() bool {
	if o != nil && o.Priority.IsSet() {
		return true
	}

	return false
}

// SetPriority gets a reference to the given NullableInt32 and assigns it to the Priority field.
func (o *ReviewCaseData) SetPriority(v int32) {
	o.Priority.Set(&v)
}

// SetPriorityNil sets the value for Priority to be an explicit nil
func (o *ReviewCaseData) SetPriorityNil() {
	o.Priority.Set(nil)
}

// UnsetPriority ensures that no value is present for Priority, not even an explicit nil
func (o *ReviewCaseData) UnsetPriority() {
	o.Priority.Unset()
}

// GetBehavior returns the Behavior field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReviewCaseData) GetBehavior() int32 {
	if o == nil || IsNil(o.Behavior.Get()) {
		var ret int32
		return ret
	}
	return *o.Behavior.Get()
}

// GetBehaviorOk returns a tuple with the Behavior field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReviewCaseData) GetBehaviorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Behavior.Get(), o.Behavior.IsSet()
}

// HasBehavior returns a boolean if a field has been set.
func (o *ReviewCaseData) HasBehavior() bool {
	if o != nil && o.Behavior.IsSet() {
		return true
	}

	return false
}

// SetBehavior gets a reference to the given NullableInt32 and assigns it to the Behavior field.
func (o *ReviewCaseData) SetBehavior(v int32) {
	o.Behavior.Set(&v)
}

// SetBehaviorNil sets the value for Behavior to be an explicit nil
func (o *ReviewCaseData) SetBehaviorNil() {
	o.Behavior.Set(nil)
}

// UnsetBehavior ensures that no value is present for Behavior, not even an explicit nil
func (o *ReviewCaseData) UnsetBehavior() {
	o.Behavior.Unset()
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReviewCaseData) GetType() int32 {
	if o == nil || IsNil(o.Type.Get()) {
		var ret int32
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReviewCaseData) GetTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *ReviewCaseData) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableInt32 and assigns it to the Type field.
func (o *ReviewCaseData) SetType(v int32) {
	o.Type.Set(&v)
}

// SetTypeNil sets the value for Type to be an explicit nil
func (o *ReviewCaseData) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *ReviewCaseData) UnsetType() {
	o.Type.Unset()
}

// GetLayer returns the Layer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReviewCaseData) GetLayer() int32 {
	if o == nil || IsNil(o.Layer.Get()) {
		var ret int32
		return ret
	}
	return *o.Layer.Get()
}

// GetLayerOk returns a tuple with the Layer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReviewCaseData) GetLayerOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Layer.Get(), o.Layer.IsSet()
}

// HasLayer returns a boolean if a field has been set.
func (o *ReviewCaseData) HasLayer() bool {
	if o != nil && o.Layer.IsSet() {
		return true
	}

	return false
}

// SetLayer gets a reference to the given NullableInt32 and assigns it to the Layer field.
func (o *ReviewCaseData) SetLayer(v int32) {
	o.Layer.Set(&v)
}

// SetLayerNil sets the value for Layer to be an explicit nil
func (o *ReviewCaseData) SetLayerNil() {
	o.Layer.Set(nil)
}

// UnsetLayer ensures that no value is present for Layer, not even an explicit nil
func (o *ReviewCaseData) UnsetLayer() {
	o.Layer.Unset()
}

// GetIsFlaky returns the IsFlaky field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReviewCaseData) GetIsFlaky() int32 {
	if o == nil || IsNil(o.IsFlaky.Get()) {
		var ret int32
		return ret
	}
	return *o.IsFlaky.Get()
}

// GetIsFlakyOk returns a tuple with the IsFlaky field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReviewCaseData) GetIsFlakyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsFlaky.Get(), o.IsFlaky.IsSet()
}

// HasIsFlaky returns a boolean if a field has been set.
func (o *ReviewCaseData) HasIsFlaky() bool {
	if o != nil && o.IsFlaky.IsSet() {
		return true
	}

	return false
}

// SetIsFlaky gets a reference to the given NullableInt32 and assigns it to the IsFlaky field.
func (o *ReviewCaseData) SetIsFlaky(v int32) {
	o.IsFlaky.Set(&v)
}

// SetIsFlakyNil sets the value for IsFlaky to be an explicit nil
func (o *ReviewCaseData) SetIsFlakyNil() {
	o.IsFlaky.Set(nil)
}

// UnsetIsFlaky ensures that no value is present for IsFlaky, not even an explicit nil
func (o *ReviewCaseData) UnsetIsFlaky() {
	o.IsFlaky.Unset()
}

// GetIsMuted returns the IsMuted field value if set, zero value otherwise.
func (o *ReviewCaseData) GetIsMuted() bool {
	if o == nil || IsNil(o.IsMuted) {
		var ret bool
		return ret
	}
	return *o.IsMuted
}

// GetIsMutedOk returns a tuple with the IsMuted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewCaseData) GetIsMutedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsMuted) {
		return nil, false
	}
	return o.IsMuted, true
}

// HasIsMuted returns a boolean if a field has been set.
func (o *ReviewCaseData) HasIsMuted() bool {
	if o != nil && !IsNil(o.IsMuted) {
		return true
	}

	return false
}

// SetIsMuted gets a reference to the given bool and assigns it to the IsMuted field.
func (o *ReviewCaseData) SetIsMuted(v bool) {
	o.IsMuted = &v
}

// GetSuiteId returns the SuiteId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReviewCaseData) GetSuiteId() int64 {
	if o == nil || IsNil(o.SuiteId.Get()) {
		var ret int64
		return ret
	}
	return *o.SuiteId.Get()
}

// GetSuiteIdOk returns a tuple with the SuiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReviewCaseData) GetSuiteIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.SuiteId.Get(), o.SuiteId.IsSet()
}

// HasSuiteId returns a boolean if a field has been set.
func (o *ReviewCaseData) HasSuiteId() bool {
	if o != nil && o.SuiteId.IsSet() {
		return true
	}

	return false
}

// SetSuiteId gets a reference to the given NullableInt64 and assigns it to the SuiteId field.
func (o *ReviewCaseData) SetSuiteId(v int64) {
	o.SuiteId.Set(&v)
}

// SetSuiteIdNil sets the value for SuiteId to be an explicit nil
func (o *ReviewCaseData) SetSuiteIdNil() {
	o.SuiteId.Set(nil)
}

// UnsetSuiteId ensures that no value is present for SuiteId, not even an explicit nil
func (o *ReviewCaseData) UnsetSuiteId() {
	o.SuiteId.Unset()
}

// GetMilestoneId returns the MilestoneId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReviewCaseData) GetMilestoneId() int64 {
	if o == nil || IsNil(o.MilestoneId.Get()) {
		var ret int64
		return ret
	}
	return *o.MilestoneId.Get()
}

// GetMilestoneIdOk returns a tuple with the MilestoneId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReviewCaseData) GetMilestoneIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.MilestoneId.Get(), o.MilestoneId.IsSet()
}

// HasMilestoneId returns a boolean if a field has been set.
func (o *ReviewCaseData) HasMilestoneId() bool {
	if o != nil && o.MilestoneId.IsSet() {
		return true
	}

	return false
}

// SetMilestoneId gets a reference to the given NullableInt64 and assigns it to the MilestoneId field.
func (o *ReviewCaseData) SetMilestoneId(v int64) {
	o.MilestoneId.Set(&v)
}

// SetMilestoneIdNil sets the value for MilestoneId to be an explicit nil
func (o *ReviewCaseData) SetMilestoneIdNil() {
	o.MilestoneId.Set(nil)
}

// UnsetMilestoneId ensures that no value is present for MilestoneId, not even an explicit nil
func (o *ReviewCaseData) UnsetMilestoneId() {
	o.MilestoneId.Unset()
}

// GetIsManual returns the IsManual field value if set, zero value otherwise.
func (o *ReviewCaseData) GetIsManual() bool {
	if o == nil || IsNil(o.IsManual) {
		var ret bool
		return ret
	}
	return *o.IsManual
}

// GetIsManualOk returns a tuple with the IsManual field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewCaseData) GetIsManualOk() (*bool, bool) {
	if o == nil || IsNil(o.IsManual) {
		return nil, false
	}
	return o.IsManual, true
}

// HasIsManual returns a boolean if a field has been set.
func (o *ReviewCaseData) HasIsManual() bool {
	if o != nil && !IsNil(o.IsManual) {
		return true
	}

	return false
}

// SetIsManual gets a reference to the given bool and assigns it to the IsManual field.
func (o *ReviewCaseData) SetIsManual(v bool) {
	o.IsManual = &v
}

// GetIsToBeAutomated returns the IsToBeAutomated field value if set, zero value otherwise.
func (o *ReviewCaseData) GetIsToBeAutomated() bool {
	if o == nil || IsNil(o.IsToBeAutomated) {
		var ret bool
		return ret
	}
	return *o.IsToBeAutomated
}

// GetIsToBeAutomatedOk returns a tuple with the IsToBeAutomated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewCaseData) GetIsToBeAutomatedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsToBeAutomated) {
		return nil, false
	}
	return o.IsToBeAutomated, true
}

// HasIsToBeAutomated returns a boolean if a field has been set.
func (o *ReviewCaseData) HasIsToBeAutomated() bool {
	if o != nil && !IsNil(o.IsToBeAutomated) {
		return true
	}

	return false
}

// SetIsToBeAutomated gets a reference to the given bool and assigns it to the IsToBeAutomated field.
func (o *ReviewCaseData) SetIsToBeAutomated(v bool) {
	o.IsToBeAutomated = &v
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReviewCaseData) GetStatus() int32 {
	if o == nil || IsNil(o.Status.Get()) {
		var ret int32
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReviewCaseData) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *ReviewCaseData) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableInt32 and assigns it to the Status field.
func (o *ReviewCaseData) SetStatus(v int32) {
	o.Status.Set(&v)
}

// SetStatusNil sets the value for Status to be an explicit nil
func (o *ReviewCaseData) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *ReviewCaseData) UnsetStatus() {
	o.Status.Unset()
}

// GetStepsType returns the StepsType field value if set, zero value otherwise.
func (o *ReviewCaseData) GetStepsType() string {
	if o == nil || IsNil(o.StepsType) {
		var ret string
		return ret
	}
	return *o.StepsType
}

// GetStepsTypeOk returns a tuple with the StepsType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewCaseData) GetStepsTypeOk() (*string, bool) {
	if o == nil || IsNil(o.StepsType) {
		return nil, false
	}
	return o.StepsType, true
}

// HasStepsType returns a boolean if a field has been set.
func (o *ReviewCaseData) HasStepsType() bool {
	if o != nil && !IsNil(o.StepsType) {
		return true
	}

	return false
}

// SetStepsType gets a reference to the given string and assigns it to the StepsType field.
func (o *ReviewCaseData) SetStepsType(v string) {
	o.StepsType = &v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *ReviewCaseData) GetAttachments() []string {
	if o == nil || IsNil(o.Attachments) {
		var ret []string
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewCaseData) GetAttachmentsOk() ([]string, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *ReviewCaseData) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []string and assigns it to the Attachments field.
func (o *ReviewCaseData) SetAttachments(v []string) {
	o.Attachments = v
}

// GetSteps returns the Steps field value if set, zero value otherwise.
func (o *ReviewCaseData) GetSteps() []ReviewStepData {
	if o == nil || IsNil(o.Steps) {
		var ret []ReviewStepData
		return ret
	}
	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewCaseData) GetStepsOk() ([]ReviewStepData, bool) {
	if o == nil || IsNil(o.Steps) {
		return nil, false
	}
	return o.Steps, true
}

// HasSteps returns a boolean if a field has been set.
func (o *ReviewCaseData) HasSteps() bool {
	if o != nil && !IsNil(o.Steps) {
		return true
	}

	return false
}

// SetSteps gets a reference to the given []ReviewStepData and assigns it to the Steps field.
func (o *ReviewCaseData) SetSteps(v []ReviewStepData) {
	o.Steps = v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReviewCaseData) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReviewCaseData) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ReviewCaseData) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *ReviewCaseData) SetTags(v []string) {
	o.Tags = v
}

// GetParameters returns the Parameters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReviewCaseData) GetParameters() []TestCaseParameterCreate {
	if o == nil {
		var ret []TestCaseParameterCreate
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReviewCaseData) GetParametersOk() ([]TestCaseParameterCreate, bool) {
	if o == nil || IsNil(o.Parameters) {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *ReviewCaseData) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given []TestCaseParameterCreate and assigns it to the Parameters field.
func (o *ReviewCaseData) SetParameters(v []TestCaseParameterCreate) {
	o.Parameters = v
}

// GetCustomField returns the CustomField field value if set, zero value otherwise.
func (o *ReviewCaseData) GetCustomField() map[string]string {
	if o == nil || IsNil(o.CustomField) {
		var ret map[string]string
		return ret
	}
	return *o.CustomField
}

// GetCustomFieldOk returns a tuple with the CustomField field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewCaseData) GetCustomFieldOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.CustomField) {
		return nil, false
	}
	return o.CustomField, true
}

// HasCustomField returns a boolean if a field has been set.
func (o *ReviewCaseData) HasCustomField() bool {
	if o != nil && !IsNil(o.CustomField) {
		return true
	}

	return false
}

// SetCustomField gets a reference to the given map[string]string and assigns it to the CustomField field.
func (o *ReviewCaseData) SetCustomField(v map[string]string) {
	o.CustomField = &v
}

func (o ReviewCaseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReviewCaseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Preconditions.IsSet() {
		toSerialize["preconditions"] = o.Preconditions.Get()
	}
	if o.Postconditions.IsSet() {
		toSerialize["postconditions"] = o.Postconditions.Get()
	}
	if o.Severity.IsSet() {
		toSerialize["severity"] = o.Severity.Get()
	}
	if o.Priority.IsSet() {
		toSerialize["priority"] = o.Priority.Get()
	}
	if o.Behavior.IsSet() {
		toSerialize["behavior"] = o.Behavior.Get()
	}
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}
	if o.Layer.IsSet() {
		toSerialize["layer"] = o.Layer.Get()
	}
	if o.IsFlaky.IsSet() {
		toSerialize["is_flaky"] = o.IsFlaky.Get()
	}
	if !IsNil(o.IsMuted) {
		toSerialize["is_muted"] = o.IsMuted
	}
	if o.SuiteId.IsSet() {
		toSerialize["suite_id"] = o.SuiteId.Get()
	}
	if o.MilestoneId.IsSet() {
		toSerialize["milestone_id"] = o.MilestoneId.Get()
	}
	if !IsNil(o.IsManual) {
		toSerialize["is_manual"] = o.IsManual
	}
	if !IsNil(o.IsToBeAutomated) {
		toSerialize["is_to_be_automated"] = o.IsToBeAutomated
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if !IsNil(o.StepsType) {
		toSerialize["steps_type"] = o.StepsType
	}
	if !IsNil(o.Attachments) {
		toSerialize["attachments"] = o.Attachments
	}
	if !IsNil(o.Steps) {
		toSerialize["steps"] = o.Steps
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.Parameters != nil {
		toSerialize["parameters"] = o.Parameters
	}
	if !IsNil(o.CustomField) {
		toSerialize["custom_field"] = o.CustomField
	}
	return toSerialize, nil
}

type NullableReviewCaseData struct {
	value *ReviewCaseData
	isSet bool
}

func (v NullableReviewCaseData) Get() *ReviewCaseData {
	return v.value
}

func (v *NullableReviewCaseData) Set(val *ReviewCaseData) {
	v.value = val
	v.isSet = true
}

func (v NullableReviewCaseData) IsSet() bool {
	return v.isSet
}

func (v *NullableReviewCaseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReviewCaseData(val *ReviewCaseData) *NullableReviewCaseData {
	return &NullableReviewCaseData{value: val, isSet: true}
}

func (v NullableReviewCaseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReviewCaseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
