name: Qase Go Reporter

on:
  push:
    paths:
      - 'pkg/qase-go/**'
  pull_request:
    paths:
      - 'pkg/qase-go/**'

env:
  GO_VERSION: '1.21'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21', '1.22' ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod download
        working-directory: pkg/qase-go

      - name: Build
        run: go build -v ./...
        working-directory: pkg/qase-go

      - name: Run tests
        run: go test -v -race -cover ./config
        working-directory: pkg/qase-go

      - name: Test examples
        run: go run examples/basic_usage.go
        working-directory: pkg/qase-go